#!/bin/bash
export EJB_JAR=$DEPLOYMENT_DIR/safety-monitoring-ejb-1.0.0.jar
export JAR_FILE_ONE=$GLASSFISH_HOME/lib/gf-client.jar
export DERBY_INSTALL_LOC=$INSTALL_DIR/$GLASSFISH_ARCHIVE/javadb
java -classpath "$EJB_JAR:$JAR_FILE_ONE" -DAS_DERBY_INSTALL=$DERBY_INSTALL_LOC safety_monitoring.PopulateServers
